//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfApp.SearchSv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phim", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class Phim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dao_dienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dien_vienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dao_dien {
            get {
                return this.Dao_dienField;
            }
            set {
                if ((object.ReferenceEquals(this.Dao_dienField, value) != true)) {
                    this.Dao_dienField = value;
                    this.RaisePropertyChanged("Dao_dien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dien_vien {
            get {
                return this.Dien_vienField;
            }
            set {
                if ((object.ReferenceEquals(this.Dien_vienField, value) != true)) {
                    this.Dien_vienField = value;
                    this.RaisePropertyChanged("Dien_vien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchSv.ISearchService")]
    public interface ISearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/DocTatCa", ReplyAction="http://tempuri.org/ISearchService/DocTatCaResponse")]
        WcfApp.SearchSv.Phim[] DocTatCa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/DocTatCa", ReplyAction="http://tempuri.org/ISearchService/DocTatCaResponse")]
        System.Threading.Tasks.Task<WcfApp.SearchSv.Phim[]> DocTatCaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/DocTheLoai", ReplyAction="http://tempuri.org/ISearchService/DocTheLoaiResponse")]
        string[] DocTheLoai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/DocTheLoai", ReplyAction="http://tempuri.org/ISearchService/DocTheLoaiResponse")]
        System.Threading.Tasks.Task<string[]> DocTheLoaiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/DocPhimTheoTheLoai", ReplyAction="http://tempuri.org/ISearchService/DocPhimTheoTheLoaiResponse")]
        WcfApp.SearchSv.Phim[] DocPhimTheoTheLoai(string theloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/DocPhimTheoTheLoai", ReplyAction="http://tempuri.org/ISearchService/DocPhimTheoTheLoaiResponse")]
        System.Threading.Tasks.Task<WcfApp.SearchSv.Phim[]> DocPhimTheoTheLoaiAsync(string theloai);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchServiceChannel : WcfApp.SearchSv.ISearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<WcfApp.SearchSv.ISearchService>, WcfApp.SearchSv.ISearchService {
        
        public SearchServiceClient() {
        }
        
        public SearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfApp.SearchSv.Phim[] DocTatCa() {
            return base.Channel.DocTatCa();
        }
        
        public System.Threading.Tasks.Task<WcfApp.SearchSv.Phim[]> DocTatCaAsync() {
            return base.Channel.DocTatCaAsync();
        }
        
        public string[] DocTheLoai() {
            return base.Channel.DocTheLoai();
        }
        
        public System.Threading.Tasks.Task<string[]> DocTheLoaiAsync() {
            return base.Channel.DocTheLoaiAsync();
        }
        
        public WcfApp.SearchSv.Phim[] DocPhimTheoTheLoai(string theloai) {
            return base.Channel.DocPhimTheoTheLoai(theloai);
        }
        
        public System.Threading.Tasks.Task<WcfApp.SearchSv.Phim[]> DocPhimTheoTheLoaiAsync(string theloai) {
            return base.Channel.DocPhimTheoTheLoaiAsync(theloai);
        }
    }
}
