//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfApp.ServiceCaChieu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaChieu", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class CaChieu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Gio_bat_dauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Phut_bat_dauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int So_phutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gio_bat_dau {
            get {
                return this.Gio_bat_dauField;
            }
            set {
                if ((this.Gio_bat_dauField.Equals(value) != true)) {
                    this.Gio_bat_dauField = value;
                    this.RaisePropertyChanged("Gio_bat_dau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phut_bat_dau {
            get {
                return this.Phut_bat_dauField;
            }
            set {
                if ((this.Phut_bat_dauField.Equals(value) != true)) {
                    this.Phut_bat_dauField = value;
                    this.RaisePropertyChanged("Phut_bat_dau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int So_phut {
            get {
                return this.So_phutField;
            }
            set {
                if ((this.So_phutField.Equals(value) != true)) {
                    this.So_phutField = value;
                    this.RaisePropertyChanged("So_phut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCaChieu.IServiceCaChieu")]
    public interface IServiceCaChieu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCaChieu/xuatCaChieu", ReplyAction="http://tempuri.org/IServiceCaChieu/xuatCaChieuResponse")]
        WcfApp.ServiceCaChieu.CaChieu[] xuatCaChieu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCaChieu/xuatCaChieu", ReplyAction="http://tempuri.org/IServiceCaChieu/xuatCaChieuResponse")]
        System.Threading.Tasks.Task<WcfApp.ServiceCaChieu.CaChieu[]> xuatCaChieuAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCaChieuChannel : WcfApp.ServiceCaChieu.IServiceCaChieu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCaChieuClient : System.ServiceModel.ClientBase<WcfApp.ServiceCaChieu.IServiceCaChieu>, WcfApp.ServiceCaChieu.IServiceCaChieu {
        
        public ServiceCaChieuClient() {
        }
        
        public ServiceCaChieuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCaChieuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCaChieuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCaChieuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfApp.ServiceCaChieu.CaChieu[] xuatCaChieu() {
            return base.Channel.xuatCaChieu();
        }
        
        public System.Threading.Tasks.Task<WcfApp.ServiceCaChieu.CaChieu[]> xuatCaChieuAsync() {
            return base.Channel.xuatCaChieuAsync();
        }
    }
}
