//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfApp.ServiceDangNhap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NguoiDung", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class NguoiDung : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_NHOM_NGUOI_DUNGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mat_khauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_NHOM_NGUOI_DUNG {
            get {
                return this.ID_NHOM_NGUOI_DUNGField;
            }
            set {
                if ((this.ID_NHOM_NGUOI_DUNGField.Equals(value) != true)) {
                    this.ID_NHOM_NGUOI_DUNGField = value;
                    this.RaisePropertyChanged("ID_NHOM_NGUOI_DUNG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mat_khau {
            get {
                return this.Mat_khauField;
            }
            set {
                if ((object.ReferenceEquals(this.Mat_khauField, value) != true)) {
                    this.Mat_khauField = value;
                    this.RaisePropertyChanged("Mat_khau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDangNhap.IServiceDangNhap")]
    public interface IServiceDangNhap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDangNhap/dangnhap", ReplyAction="http://tempuri.org/IServiceDangNhap/dangnhapResponse")]
        WcfApp.ServiceDangNhap.NguoiDung dangnhap(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDangNhap/dangnhap", ReplyAction="http://tempuri.org/IServiceDangNhap/dangnhapResponse")]
        System.Threading.Tasks.Task<WcfApp.ServiceDangNhap.NguoiDung> dangnhapAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDangNhap/dangky", ReplyAction="http://tempuri.org/IServiceDangNhap/dangkyResponse")]
        string dangky(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDangNhap/dangky", ReplyAction="http://tempuri.org/IServiceDangNhap/dangkyResponse")]
        System.Threading.Tasks.Task<string> dangkyAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDangNhap/lietke", ReplyAction="http://tempuri.org/IServiceDangNhap/lietkeResponse")]
        WcfApp.ServiceDangNhap.NguoiDung[] lietke();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDangNhap/lietke", ReplyAction="http://tempuri.org/IServiceDangNhap/lietkeResponse")]
        System.Threading.Tasks.Task<WcfApp.ServiceDangNhap.NguoiDung[]> lietkeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDangNhapChannel : WcfApp.ServiceDangNhap.IServiceDangNhap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDangNhapClient : System.ServiceModel.ClientBase<WcfApp.ServiceDangNhap.IServiceDangNhap>, WcfApp.ServiceDangNhap.IServiceDangNhap {
        
        public ServiceDangNhapClient() {
        }
        
        public ServiceDangNhapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDangNhapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDangNhapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDangNhapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfApp.ServiceDangNhap.NguoiDung dangnhap(string username, string password) {
            return base.Channel.dangnhap(username, password);
        }
        
        public System.Threading.Tasks.Task<WcfApp.ServiceDangNhap.NguoiDung> dangnhapAsync(string username, string password) {
            return base.Channel.dangnhapAsync(username, password);
        }
        
        public string dangky(string username, string password) {
            return base.Channel.dangky(username, password);
        }
        
        public System.Threading.Tasks.Task<string> dangkyAsync(string username, string password) {
            return base.Channel.dangkyAsync(username, password);
        }
        
        public WcfApp.ServiceDangNhap.NguoiDung[] lietke() {
            return base.Channel.lietke();
        }
        
        public System.Threading.Tasks.Task<WcfApp.ServiceDangNhap.NguoiDung[]> lietkeAsync() {
            return base.Channel.lietkeAsync();
        }
    }
}
