//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfApp.WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CongTy", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class CongTy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dia_chiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dien_thoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int So_tuan_lap_lichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dia_chi {
            get {
                return this.Dia_chiField;
            }
            set {
                if ((object.ReferenceEquals(this.Dia_chiField, value) != true)) {
                    this.Dia_chiField = value;
                    this.RaisePropertyChanged("Dia_chi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dien_thoai {
            get {
                return this.Dien_thoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.Dien_thoaiField, value) != true)) {
                    this.Dien_thoaiField = value;
                    this.RaisePropertyChanged("Dien_thoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int So_tuan_lap_lich {
            get {
                return this.So_tuan_lap_lichField;
            }
            set {
                if ((this.So_tuan_lap_lichField.Equals(value) != true)) {
                    this.So_tuan_lap_lichField = value;
                    this.RaisePropertyChanged("So_tuan_lap_lich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CONG_TY", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class CONG_TY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dia_chiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dien_thoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int So_tuan_lap_lichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dia_chi {
            get {
                return this.Dia_chiField;
            }
            set {
                if ((object.ReferenceEquals(this.Dia_chiField, value) != true)) {
                    this.Dia_chiField = value;
                    this.RaisePropertyChanged("Dia_chi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dien_thoai {
            get {
                return this.Dien_thoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.Dien_thoaiField, value) != true)) {
                    this.Dien_thoaiField = value;
                    this.RaisePropertyChanged("Dien_thoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int So_tuan_lap_lich {
            get {
                return this.So_tuan_lap_lichField;
            }
            set {
                if ((this.So_tuan_lap_lichField.Equals(value) != true)) {
                    this.So_tuan_lap_lichField = value;
                    this.RaisePropertyChanged("So_tuan_lap_lich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IServiceCongTy")]
    public interface IServiceCongTy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/DocTheoId", ReplyAction="http://tempuri.org/IServiceCongTy/DocTheoIdResponse")]
        WcfApp.WcfService.CongTy DocTheoId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/DocTheoId", ReplyAction="http://tempuri.org/IServiceCongTy/DocTheoIdResponse")]
        System.Threading.Tasks.Task<WcfApp.WcfService.CongTy> DocTheoIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/DocTatCa", ReplyAction="http://tempuri.org/IServiceCongTy/DocTatCaResponse")]
        WcfApp.WcfService.CongTy[] DocTatCa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/DocTatCa", ReplyAction="http://tempuri.org/IServiceCongTy/DocTatCaResponse")]
        System.Threading.Tasks.Task<WcfApp.WcfService.CongTy[]> DocTatCaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/Them", ReplyAction="http://tempuri.org/IServiceCongTy/ThemResponse")]
        string Them(WcfApp.WcfService.CONG_TY congty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/Them", ReplyAction="http://tempuri.org/IServiceCongTy/ThemResponse")]
        System.Threading.Tasks.Task<string> ThemAsync(WcfApp.WcfService.CONG_TY congty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/Sua", ReplyAction="http://tempuri.org/IServiceCongTy/SuaResponse")]
        string Sua(WcfApp.WcfService.CongTy congty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/Sua", ReplyAction="http://tempuri.org/IServiceCongTy/SuaResponse")]
        System.Threading.Tasks.Task<string> SuaAsync(WcfApp.WcfService.CongTy congty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/Huy", ReplyAction="http://tempuri.org/IServiceCongTy/HuyResponse")]
        string Huy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCongTy/Huy", ReplyAction="http://tempuri.org/IServiceCongTy/HuyResponse")]
        System.Threading.Tasks.Task<string> HuyAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCongTyChannel : WcfApp.WcfService.IServiceCongTy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCongTyClient : System.ServiceModel.ClientBase<WcfApp.WcfService.IServiceCongTy>, WcfApp.WcfService.IServiceCongTy {
        
        public ServiceCongTyClient() {
        }
        
        public ServiceCongTyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCongTyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCongTyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCongTyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfApp.WcfService.CongTy DocTheoId(int id) {
            return base.Channel.DocTheoId(id);
        }
        
        public System.Threading.Tasks.Task<WcfApp.WcfService.CongTy> DocTheoIdAsync(int id) {
            return base.Channel.DocTheoIdAsync(id);
        }
        
        public WcfApp.WcfService.CongTy[] DocTatCa() {
            return base.Channel.DocTatCa();
        }
        
        public System.Threading.Tasks.Task<WcfApp.WcfService.CongTy[]> DocTatCaAsync() {
            return base.Channel.DocTatCaAsync();
        }
        
        public string Them(WcfApp.WcfService.CONG_TY congty) {
            return base.Channel.Them(congty);
        }
        
        public System.Threading.Tasks.Task<string> ThemAsync(WcfApp.WcfService.CONG_TY congty) {
            return base.Channel.ThemAsync(congty);
        }
        
        public string Sua(WcfApp.WcfService.CongTy congty) {
            return base.Channel.Sua(congty);
        }
        
        public System.Threading.Tasks.Task<string> SuaAsync(WcfApp.WcfService.CongTy congty) {
            return base.Channel.SuaAsync(congty);
        }
        
        public string Huy(int id) {
            return base.Channel.Huy(id);
        }
        
        public System.Threading.Tasks.Task<string> HuyAsync(int id) {
            return base.Channel.HuyAsync(id);
        }
    }
}
