//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfApp.ServiceLichChieu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichChieu", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class LichChieu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Ngay_bat_dauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Ngay_ket_thucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoiGianField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngay_bat_dau {
            get {
                return this.Ngay_bat_dauField;
            }
            set {
                if ((this.Ngay_bat_dauField.Equals(value) != true)) {
                    this.Ngay_bat_dauField = value;
                    this.RaisePropertyChanged("Ngay_bat_dau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngay_ket_thuc {
            get {
                return this.Ngay_ket_thucField;
            }
            set {
                if ((this.Ngay_ket_thucField.Equals(value) != true)) {
                    this.Ngay_ket_thucField = value;
                    this.RaisePropertyChanged("Ngay_ket_thuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThoiGian {
            get {
                return this.ThoiGianField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoiGianField, value) != true)) {
                    this.ThoiGianField = value;
                    this.RaisePropertyChanged("ThoiGian");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLichChieu.IServiceLichChieu")]
    public interface IServiceLichChieu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLichChieu/DocTatCa", ReplyAction="http://tempuri.org/IServiceLichChieu/DocTatCaResponse")]
        WcfApp.ServiceLichChieu.LichChieu[] DocTatCa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLichChieu/DocTatCa", ReplyAction="http://tempuri.org/IServiceLichChieu/DocTatCaResponse")]
        System.Threading.Tasks.Task<WcfApp.ServiceLichChieu.LichChieu[]> DocTatCaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLichChieuChannel : WcfApp.ServiceLichChieu.IServiceLichChieu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLichChieuClient : System.ServiceModel.ClientBase<WcfApp.ServiceLichChieu.IServiceLichChieu>, WcfApp.ServiceLichChieu.IServiceLichChieu {
        
        public ServiceLichChieuClient() {
        }
        
        public ServiceLichChieuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLichChieuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLichChieuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLichChieuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfApp.ServiceLichChieu.LichChieu[] DocTatCa() {
            return base.Channel.DocTatCa();
        }
        
        public System.Threading.Tasks.Task<WcfApp.ServiceLichChieu.LichChieu[]> DocTatCaAsync() {
            return base.Channel.DocTatCaAsync();
        }
    }
}
