//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_GOM
    {
        public int ID { get; set; }
        public int ID_LICH_CHIEU { get; set; }
        public int ID_PHIM { get; set; }
    
        public virtual LICH_CHIEU LICH_CHIEU { get; set; }
        public virtual PHIM PHIM { get; set; }
    }
}
