//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONG_TY
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Dien_thoai { get; set; }
        public string Dia_chi { get; set; }
        public int So_tuan_lap_lich { get; set; }
    }
}
