//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHE
    {
        public GHE()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public int ID { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int ID_PHONG { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual ICollection<VE> VEs { get; set; }
    }
}
