//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_CHIEU
    {
        public LICH_CHIEU()
        {
            this.BAO_GOM = new HashSet<BAO_GOM>();
            this.XUAT_CHIEU = new HashSet<XUAT_CHIEU>();
        }
    
        public int ID { get; set; }
        public System.DateTime Ngay_bat_dau { get; set; }
        public System.DateTime Ngay_ket_thuc { get; set; }
    
        public virtual ICollection<BAO_GOM> BAO_GOM { get; set; }
        public virtual ICollection<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
