//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WcfDbContext : DbContext
    {
        public WcfDbContext()
            : base("name=WcfDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAO_GOM> BAO_GOM { get; set; }
        public virtual DbSet<CA_CHIEU> CA_CHIEU { get; set; }
        public virtual DbSet<CONG_TY> CONG_TY { get; set; }
        public virtual DbSet<GHE> GHEs { get; set; }
        public virtual DbSet<LICH_CHIEU> LICH_CHIEU { get; set; }
        public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual DbSet<NHOM_NGUOI_DUNG> NHOM_NGUOI_DUNG { get; set; }
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<VE> VEs { get; set; }
        public virtual DbSet<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
