//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_NGUOI_DUNG
    {
        public NHOM_NGUOI_DUNG()
        {
            this.NGUOI_DUNG = new HashSet<NGUOI_DUNG>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Ma_so { get; set; }
    
        public virtual ICollection<NGUOI_DUNG> NGUOI_DUNG { get; set; }
    }
}
