//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public PHONG()
        {
            this.GHEs = new HashSet<GHE>();
            this.XUAT_CHIEU = new HashSet<XUAT_CHIEU>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
    
        public virtual ICollection<GHE> GHEs { get; set; }
        public virtual ICollection<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
