//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN_HAN
    {
        public int STT { get; set; }
        public Nullable<int> MA_NHOM { get; set; }
        public string CHUC_NANG { get; set; }
        public Nullable<bool> QUYEN { get; set; }
        public string GHI_CHU { get; set; }
    }
}
