//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public int ID { get; set; }
        public bool Trang_thai { get; set; }
        public int ID_XUAT_CHIEU { get; set; }
        public int ID_GHE { get; set; }
        public Nullable<decimal> Gia_tien { get; set; }
        public string ID_NGUOI_DUNG { get; set; }
    
        public virtual GHE GHE { get; set; }
        public virtual XUAT_CHIEU XUAT_CHIEU { get; set; }
    }
}
