//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfApp.ServiceMovie {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phim", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class Phim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dao_dienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dien_vienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dao_dien {
            get {
                return this.Dao_dienField;
            }
            set {
                if ((object.ReferenceEquals(this.Dao_dienField, value) != true)) {
                    this.Dao_dienField = value;
                    this.RaisePropertyChanged("Dao_dien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dien_vien {
            get {
                return this.Dien_vienField;
            }
            set {
                if ((object.ReferenceEquals(this.Dien_vienField, value) != true)) {
                    this.Dien_vienField = value;
                    this.RaisePropertyChanged("Dien_vien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PHIM_ALL", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class PHIM_ALL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dao_dienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dien_vienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Do_daiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Gioi_thieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hang_phimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nuoc_san_xuatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phien_banField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string The_loaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrailerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dao_dien {
            get {
                return this.Dao_dienField;
            }
            set {
                if ((object.ReferenceEquals(this.Dao_dienField, value) != true)) {
                    this.Dao_dienField = value;
                    this.RaisePropertyChanged("Dao_dien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dien_vien {
            get {
                return this.Dien_vienField;
            }
            set {
                if ((object.ReferenceEquals(this.Dien_vienField, value) != true)) {
                    this.Dien_vienField = value;
                    this.RaisePropertyChanged("Dien_vien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Do_dai {
            get {
                return this.Do_daiField;
            }
            set {
                if ((this.Do_daiField.Equals(value) != true)) {
                    this.Do_daiField = value;
                    this.RaisePropertyChanged("Do_dai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gioi_thieu {
            get {
                return this.Gioi_thieuField;
            }
            set {
                if ((object.ReferenceEquals(this.Gioi_thieuField, value) != true)) {
                    this.Gioi_thieuField = value;
                    this.RaisePropertyChanged("Gioi_thieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hang_phim {
            get {
                return this.Hang_phimField;
            }
            set {
                if ((object.ReferenceEquals(this.Hang_phimField, value) != true)) {
                    this.Hang_phimField = value;
                    this.RaisePropertyChanged("Hang_phim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nuoc_san_xuat {
            get {
                return this.Nuoc_san_xuatField;
            }
            set {
                if ((object.ReferenceEquals(this.Nuoc_san_xuatField, value) != true)) {
                    this.Nuoc_san_xuatField = value;
                    this.RaisePropertyChanged("Nuoc_san_xuat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PDF {
            get {
                return this.PDFField;
            }
            set {
                if ((object.ReferenceEquals(this.PDFField, value) != true)) {
                    this.PDFField = value;
                    this.RaisePropertyChanged("PDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phien_ban {
            get {
                return this.Phien_banField;
            }
            set {
                if ((object.ReferenceEquals(this.Phien_banField, value) != true)) {
                    this.Phien_banField = value;
                    this.RaisePropertyChanged("Phien_ban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Poster {
            get {
                return this.PosterField;
            }
            set {
                if ((object.ReferenceEquals(this.PosterField, value) != true)) {
                    this.PosterField = value;
                    this.RaisePropertyChanged("Poster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string The_loai {
            get {
                return this.The_loaiField;
            }
            set {
                if ((object.ReferenceEquals(this.The_loaiField, value) != true)) {
                    this.The_loaiField = value;
                    this.RaisePropertyChanged("The_loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trailer {
            get {
                return this.TrailerField;
            }
            set {
                if ((object.ReferenceEquals(this.TrailerField, value) != true)) {
                    this.TrailerField = value;
                    this.RaisePropertyChanged("Trailer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMovie.IServiceMovies")]
    public interface IServiceMovies {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMovies/DocTheoLich", ReplyAction="http://tempuri.org/IServiceMovies/DocTheoLichResponse")]
        WcfApp.ServiceMovie.Phim[] DocTheoLich(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMovies/DocTheoLich", ReplyAction="http://tempuri.org/IServiceMovies/DocTheoLichResponse")]
        System.Threading.Tasks.Task<WcfApp.ServiceMovie.Phim[]> DocTheoLichAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMovies/Doctheocachieu", ReplyAction="http://tempuri.org/IServiceMovies/DoctheocachieuResponse")]
        WcfApp.ServiceMovie.PHIM_ALL[] Doctheocachieu(System.DateTime ngaychon, int id_cachon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMovies/Doctheocachieu", ReplyAction="http://tempuri.org/IServiceMovies/DoctheocachieuResponse")]
        System.Threading.Tasks.Task<WcfApp.ServiceMovie.PHIM_ALL[]> DoctheocachieuAsync(System.DateTime ngaychon, int id_cachon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMoviesChannel : WcfApp.ServiceMovie.IServiceMovies, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMoviesClient : System.ServiceModel.ClientBase<WcfApp.ServiceMovie.IServiceMovies>, WcfApp.ServiceMovie.IServiceMovies {
        
        public ServiceMoviesClient() {
        }
        
        public ServiceMoviesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMoviesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMoviesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMoviesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfApp.ServiceMovie.Phim[] DocTheoLich(int id) {
            return base.Channel.DocTheoLich(id);
        }
        
        public System.Threading.Tasks.Task<WcfApp.ServiceMovie.Phim[]> DocTheoLichAsync(int id) {
            return base.Channel.DocTheoLichAsync(id);
        }
        
        public WcfApp.ServiceMovie.PHIM_ALL[] Doctheocachieu(System.DateTime ngaychon, int id_cachon) {
            return base.Channel.Doctheocachieu(ngaychon, id_cachon);
        }
        
        public System.Threading.Tasks.Task<WcfApp.ServiceMovie.PHIM_ALL[]> DoctheocachieuAsync(System.DateTime ngaychon, int id_cachon) {
            return base.Channel.DoctheocachieuAsync(ngaychon, id_cachon);
        }
    }
}
